### ISSUE TITLE
Can't connect because device already connected?

### ISSUE THREAD

**Issue by trent-weiss** [iirob/microepsilon_scancontrol#3]
Hey guys, thanks for pushing this. Looks like really useful stuff.

I am trying to run your provided scanner.launch file with a MicroEpsilon ScanCONTROL 2900.

Your code seems to locate the sensor and try to connect with it, but I get really weird behavior.  I get some messages on stdout saying a device was found and whatnot, but then I get an error message saying could not connect to the device, error code -302.  I looked this up in the microepsilon API document and apparently that means "There is already a scanCONTROL connected with this id".

So, I can't connect because the device is already connected?!?!?!

I've attached a screencap of my terminal output for reference.

Any help with this would be appreciated :)

![error](https://user-images.githubusercontent.com/22912177/40390401-a8f0f290-5e04-11e8-9f77-db46a67d9ccd.png)

**Comment by hartmanndennis** [comment]
Are you already connected with the Windows tool?
