### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ozangungor12** [iirob/microepsilon_scancontrol#5]
After completing the following installation steps:

- install aravis0.4
- copy libllt.h and LLTDataTypes.h to /usr/local/include/libllt
- copy libmescan.h to /usr/local/include/libmescan
- copy libllt.so.1.0 and libmescan.so.1.0 to /usr/local/lib
- run 'sudo ldconfig' to create sofiles and adding libraries to cache

I am having this error when I build by catkin workscape with microepsilon_scancontrol package.
Any idea what is going on here?

/catkin_ws/src/microepsilon_scancontrol/src/test.cpp: In function ‘int main(int, char**)’:
//catkin_ws/src/microepsilon_scancontrol/src/test.cpp:117:24: error: found ‘:’ in nested-name-specifier, expected ‘::’
   for ( m_uiResolution : vuiResolutions )
                        ^
/catkin_ws/src/microepsilon_scancontrol/src/test.cpp:117:9: error: ‘m_uiResolution’ is not a class, namespace, or enumeration
   for ( m_uiResolution : vuiResolutions )
         ^~~~~~~~~~~~~~
/catkin_ws/src/microepsilon_scancontrol/src/test.cpp:124:37: error: expected ‘)’ before ‘;’ token
   m_uiResolution = vuiResolutions[0];

**Comment by hartmanndennis** [comment]
There is no test.cpp in this repo, so this is an error on your end. But from the error message this looks like you use C++11 features but didn't enable C++11 in CMakeLists.txt.

**Comment by ozangungor12** [comment]
Thanks for the answer!
I have add_compile_options(-std=c++11) line at the beginning of my CMakelists file, is there a better way to do it?

**Comment by hartmanndennis** [comment]
That seems to be the standard way.
